name: build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install fyne-cross
        run: go install github.com/gavintan/fyne-cross@latest

      - name: Build
        run: |
          make dist

      - name: Run upx
        uses: svenstaro/upx-action@v2
        with:
          files: |
            release/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release

  publish:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - uses: actions/download-artifact@v4
        with:
          name: release
          path: release

      - run: |
          brew install create-dmg
          make create_dmg

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
